//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public Payment()
        {
            this.Credits = new HashSet<Credit>();
            this.Efts = new HashSet<Eft>();
        }
    
        public int PaymentID { get; set; }
        public int CustomerID { get; set; }
        public string PaymentType { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Credit> Credits { get; set; }
        public virtual ICollection<Eft> Efts { get; set; }
    }
}
